{% set version = "1.1" %}

package:
  name: r-irdisplay
  version: {{ version }}

source:
  fn: r-irdisplay-{{ version }}.tar.gz
  url: https://github.com/IRkernel/IRdisplay/archive/{{ version }}.tar.gz
  sha256: 6ea9ae9f836143d42d19d5b7fc351371a09f465d230a36ce2781e46040e7040d

build:
  noarch: generic
  number: 3
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-repr
  run:
    - r-base
    - r-repr

test:
  commands:
    - R -e "library('IRdisplay')"

about:
  home: https://github.com/IRkernel/IRdisplay/
  license: MIT
  license_file: LICENSE
  summary: An interface to the rich display capabilities of 'Jupyter' front-ends (e.g. 'Jupyter Notebook'). Designed to be used from a running 'IRkernel'.

extra:
  recipe-maintainers:
    - ocefpaf
    - conda-forge/r
