{% set version = "0.6.2" %}

package:
  name: r-irdisplay
  version: {{ version }}

source:
  fn: r-irdisplay-{{ version }}.tar.gz
  url: https://github.com/IRkernel/IRdisplay/archive/{{ version }}.tar.gz
  sha256: 53a8499e7c718468fc69c6922cf39be27d2e7e688206633c4e48c908debf9ab2

build:
  noarch: generic
  number: 1000
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:  # [not win32]
  build:  # [not win32]
    - r-base  # [not win32]
    - posix  # [win64]
    - m2-git  # [win64]
    - r-repr  # [not win32]
  run:  # [not win32]
    - r-base  # [not win32]
    - r-repr  # [not win32]

test:
  commands:
    - R -e "library('IRdisplay')"  # [not win]
    - R -e \"library('IRdisplay')\"  # [win]

about:
  home: https://github.com/IRkernel/IRdisplay/
  license: MIT
  license_file: LICENSE
  summary: "An interface to the rich display capabilities of 'Jupyter' front-ends (e.g. 'Jupyter
    Notebook'). Designed to be used from a running 'IRkernel'."

extra:
  recipe-maintainers:
    - ocefpaf
