# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "aGOcSQFtgV+un7Rdng8HB/8n1pdyBHtOKKoOGG4ZvXqPJQj3G+wjhn8RtDZB+6uW2k3sIB2zlxgoUSnToxCXJxe+i1PBo9ZMvboid4LipTekS5hQs1zVDG0ke/NLyLApNbWR4T2TTfweYfp4rf8aE8nXONrL+X9FRX2rF9Ebh1Kb2gOwZfHop9eQhPMMLGBA9/e804sMuI6YNooLBDBye/ao21cl8cQkZWaMwXRi2RMueAwd9grfWh951NdIQ5OZUpyNnMherqHvq5y+TK2Xkl5VmRYXhnlrmxe9t9dv33Jiok/HL+EUf4/GElOlh1PURfkqVxi4gWb/qfmo+xMLz3z3C9/z+kRizlpgvL6B8st7feQlJ53lMpH0IYT7FXoX1mbvKcg0g9tz49KefndiFPzbu30sv/WBYH7jCLGyR5WHTOf4KJtgU5QGXW0Lcvtc8tdD1yE0NZZkSgOXzrOApoJNAzjZr1slZ08lSC6bjNBn3J/ByWSg3r9p6rWodai34ZBtbXeOWUEAjqwCt0pYkkuXgXYiRSEf7hCpAfQUdYte653GkZnR/u2a6Mt7vpXKRjOL3gtHZNy/Gm2rdGYAfe7NsP/5BTvrmfvFL082qk2HqVW0s1y+nSSxBfLpUHz7Mmf0wyWsY5ta2mnR477FBzhwcmRPtwITnvBvJGKpd4U="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
