appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: aGOcSQFtgV+un7Rdng8HB/8n1pdyBHtOKKoOGG4ZvXqPJQj3G+wjhn8RtDZB+6uW2k3sIB2zlxgoUSnToxCXJxe+i1PBo9ZMvboid4LipTekS5hQs1zVDG0ke/NLyLApNbWR4T2TTfweYfp4rf8aE8nXONrL+X9FRX2rF9Ebh1Kb2gOwZfHop9eQhPMMLGBA9/e804sMuI6YNooLBDBye/ao21cl8cQkZWaMwXRi2RMueAwd9grfWh951NdIQ5OZUpyNnMherqHvq5y+TK2Xkl5VmRYXhnlrmxe9t9dv33Jiok/HL+EUf4/GElOlh1PURfkqVxi4gWb/qfmo+xMLz3z3C9/z+kRizlpgvL6B8st7feQlJ53lMpH0IYT7FXoX1mbvKcg0g9tz49KefndiFPzbu30sv/WBYH7jCLGyR5WHTOf4KJtgU5QGXW0Lcvtc8tdD1yE0NZZkSgOXzrOApoJNAzjZr1slZ08lSC6bjNBn3J/ByWSg3r9p6rWodai34ZBtbXeOWUEAjqwCt0pYkkuXgXYiRSEf7hCpAfQUdYte653GkZnR/u2a6Mt7vpXKRjOL3gtHZNy/Gm2rdGYAfe7NsP/5BTvrmfvFL082qk2HqVW0s1y+nSSxBfLpUHz7Mmf0wyWsY5ta2mnR477FBzhwcmRPtwITnvBvJGKpd4U=}
